base: &base
  adapter: postgresql
  encoding: unicode
  reconnect: true
  host: localhost
  pool: 5
  username: postgres
  password:

development:
  <<: *base
  database: currencies
  username: deploy
  password: ENV['DB_PASSWORD']
